server:
  listen: "0.0.0.0:5000"

frontend:
  staticPath: "/app/frontend/dist"

database:
  driver: sqlite
  sqlite:
    path: "/app/data/backend.db"

media:
  driver: local
  local:
    path: "/app/data/media"

secrets:
  jwtSecret: "6a2f29d3471b66a1371d586a784863eeaaf9baac0bb4c3c13cccbd488a5252b5"
  credentialEncryptionKey: "y0h9CfEqHOnPHeEFrprGn4MiBhbykrye9oPHM7pRh1I="

bootstrapAdmin:
  username: "admin"
  password: "AdminSuperGrok2026!"
